server:
  port: 80

spring:
  application:
    name: gateway-service
  zipkin:
    base-url: http://localhost:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/login
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/join
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/logout
        - id: insurance-service
          uri: lb://insurance-service
          predicates:
            - Path=/insurance/**
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/client/**
        - id: contract-service
          uri: lb://contract-service
          predicates:
            - Path=/contract/**
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/api-docs

eureka:
  instance:
    instance-id: gateway-service
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

token:
  secret: user_token
---
spring:
  profiles: docker
  zipkin:
    base-url: http://zipkin-service:9411
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
